//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainMasterpiesce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedbackId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public string title { get; set; }
        public Nullable<int> statefeedback { get; set; }
        public Nullable<System.DateTime> feedbacktime { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
