//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainMasterpiesce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionspatient
    {
        public int transcpatientId { get; set; }
        public Nullable<int> PatiantId { get; set; }
        public string transpatienttiontype { get; set; }
        public Nullable<double> amount { get; set; }
        public string paymentmethod { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> Tansactiontime { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
